//HintName: ApiGroupAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the InventorySystem.Core.Api source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace InventorySystem.Core.Api
{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    internal class ApiGroupAttribute : System.Attribute
    {
		public ApiGroupAttribute(string route)
		{
		}
    }
    
    [System.AttributeUsage(System.AttributeTargets.Method)]
    internal class ApiGetAttribute : System.Attribute
    {
		public string Route { get; set; }
		public ApiGetAttribute(string route)
		{
			Route = route;
		}
    }
    
    [System.AttributeUsage(System.AttributeTargets.Method)]
    internal class ApiPostAttribute : System.Attribute
    {
		public ApiPostAttribute(string route)
		{
		}
    }
}